baseURL = "https://www.dwongresearch.com/"
languageCode = "en-us"
title = "DWongResearch Blog"

theme = "hugo-theme-dream"
enableRobotsTXT = true
[params]

# general
headerTitle="DWongResearch Blog"
author="dwongresearch"
description="DWongResearch Blog"

background="#fff"
motto="Untangling Our World"
email = "dwongresearch0@gmail.com"
github = "dwongresearch"
siteStartYear = 2021
twitter="dwongresearch"

avatar = "/imgs/DWongResearchLogo.png"
favicon = "/imgs/favicon.ico"
# Google Analytics 4
googleAnalyticsID = "G-LNMFPS47RB"

# search
enableSearch = true

# options
rss = true
showSummaryCoverInPost = false
hasTwitterEmbed = true
# reversePostAndAside = true
shareInAside = true
fixedNav = true
collapsibleTags = true
collapseBySummary = true

# mathjax
mathjax = true

 [params.advanced]
 customCSS = ["/css/custom.css"]

[taxonomies]
  category = 'categories'
  tag = 'tags'
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

